site_name: Cosmere RPG campaign wiki
theme:
  name: material
  palette:
    - scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle: 
        icon: material/weather-night
        name: Switch to light mode


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: home/home.md
  - Rules: rules/cheatsheet.md
  - Session Recaps: session-recaps/session-recaps.md
  - Points of Interest: points-of-interest/points-of-interest.md
  - Characters: characters/characters.md
  - Locations: locations/locations.md
